// Generated from: tests\features\checkout.feature
import { test } from "../../../tests/fixtures.js";

test.describe('Checkout', () => {

  test.beforeEach('Background', async ({ Given, And, page }, testInfo) => { if (testInfo.error) return;
    await Given('I am logged in as "standard_user" with password "secret_sauce"', null, { page }); 
    await And('I add "Sauce Labs Backpack" to the cart', null, { page }); 
    await And('I click the cart icon', null, { page }); 
  });
  
  test.describe('Checkout with multiple data sets', () => {

    test('Example #1', { tag: ['@checkout'] }, async ({ When, Then, And, page }) => { 
      await When('I click the checkout button', null, { page }); 
      await And('I enter checkout first name "Abhishek"'); 
      await And('I enter checkout last name "Gargya"'); 
      await And('I enter checkout zip code "110001"'); 
      await And('I click the continue button'); 
      await Then('I should see "order summary page"'); 
    });

    test('Example #2', { tag: ['@checkout'] }, async ({ When, Then, And, page }) => { 
      await When('I click the checkout button', null, { page }); 
      await And('I enter checkout first name ""'); 
      await And('I enter checkout last name "Gargya"'); 
      await And('I enter checkout zip code "110001"'); 
      await And('I click the continue button'); 
      await Then('I should see "Error: First Name is required"'); 
    });

    test('Example #3', { tag: ['@checkout'] }, async ({ When, Then, And, page }) => { 
      await When('I click the checkout button', null, { page }); 
      await And('I enter checkout first name "Abhishek"'); 
      await And('I enter checkout last name ""'); 
      await And('I enter checkout zip code "110001"'); 
      await And('I click the continue button'); 
      await Then('I should see "Error: Last Name is required"'); 
    });

    test('Example #4', { tag: ['@checkout'] }, async ({ When, Then, And, page }) => { 
      await When('I click the checkout button', null, { page }); 
      await And('I enter checkout first name "Abhishek"'); 
      await And('I enter checkout last name "Gargya"'); 
      await And('I enter checkout zip code ""'); 
      await And('I click the continue button'); 
      await Then('I should see "Error: Postal Code is required"'); 
    });

  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('tests\\features\\checkout.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":14,"pickleLine":19,"tags":["@checkout"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am logged in as \"standard_user\" with password \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":18,"value":"\"standard_user\"","children":[{"start":19,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"secret_sauce\"","children":[{"start":49,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And I add \"Sauce Labs Backpack\" to the cart","isBg":true,"stepMatchArguments":[{"group":{"start":6,"value":"\"Sauce Labs Backpack\"","children":[{"start":7,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I click the cart icon","isBg":true,"stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I click the checkout button","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I enter checkout first name \"Abhishek\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Abhishek\"","children":[{"start":29,"value":"Abhishek","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":17,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter checkout last name \"Gargya\"","stepMatchArguments":[{"group":{"start":27,"value":"\"Gargya\"","children":[{"start":28,"value":"Gargya","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":18,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I enter checkout zip code \"110001\"","stepMatchArguments":[{"group":{"start":26,"value":"\"110001\"","children":[{"start":27,"value":"110001","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":19,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"And I click the continue button","stepMatchArguments":[]},{"pwStepLine":20,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then I should see \"order summary page\"","stepMatchArguments":[{"group":{"start":13,"value":"\"order summary page\"","children":[{"start":14,"value":"order summary page","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":23,"pickleLine":20,"tags":["@checkout"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am logged in as \"standard_user\" with password \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":18,"value":"\"standard_user\"","children":[{"start":19,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"secret_sauce\"","children":[{"start":49,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And I add \"Sauce Labs Backpack\" to the cart","isBg":true,"stepMatchArguments":[{"group":{"start":6,"value":"\"Sauce Labs Backpack\"","children":[{"start":7,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I click the cart icon","isBg":true,"stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I click the checkout button","stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I enter checkout first name \"\"","stepMatchArguments":[{"group":{"start":28,"value":"\"\"","children":[{"start":29,"value":"","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":26,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter checkout last name \"Gargya\"","stepMatchArguments":[{"group":{"start":27,"value":"\"Gargya\"","children":[{"start":28,"value":"Gargya","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":27,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I enter checkout zip code \"110001\"","stepMatchArguments":[{"group":{"start":26,"value":"\"110001\"","children":[{"start":27,"value":"110001","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":28,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"And I click the continue button","stepMatchArguments":[]},{"pwStepLine":29,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then I should see \"Error: First Name is required\"","stepMatchArguments":[{"group":{"start":13,"value":"\"Error: First Name is required\"","children":[{"start":14,"value":"Error: First Name is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":32,"pickleLine":21,"tags":["@checkout"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am logged in as \"standard_user\" with password \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":18,"value":"\"standard_user\"","children":[{"start":19,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"secret_sauce\"","children":[{"start":49,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And I add \"Sauce Labs Backpack\" to the cart","isBg":true,"stepMatchArguments":[{"group":{"start":6,"value":"\"Sauce Labs Backpack\"","children":[{"start":7,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I click the cart icon","isBg":true,"stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I click the checkout button","stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I enter checkout first name \"Abhishek\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Abhishek\"","children":[{"start":29,"value":"Abhishek","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":35,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter checkout last name \"\"","stepMatchArguments":[{"group":{"start":27,"value":"\"\"","children":[{"start":28,"value":"","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":36,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I enter checkout zip code \"110001\"","stepMatchArguments":[{"group":{"start":26,"value":"\"110001\"","children":[{"start":27,"value":"110001","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":37,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"And I click the continue button","stepMatchArguments":[]},{"pwStepLine":38,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then I should see \"Error: Last Name is required\"","stepMatchArguments":[{"group":{"start":13,"value":"\"Error: Last Name is required\"","children":[{"start":14,"value":"Error: Last Name is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":41,"pickleLine":22,"tags":["@checkout"],"steps":[{"pwStepLine":7,"gherkinStepLine":4,"keywordType":"Context","textWithKeyword":"Given I am logged in as \"standard_user\" with password \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":18,"value":"\"standard_user\"","children":[{"start":19,"value":"standard_user","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"},{"group":{"start":48,"value":"\"secret_sauce\"","children":[{"start":49,"value":"secret_sauce","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":8,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"And I add \"Sauce Labs Backpack\" to the cart","isBg":true,"stepMatchArguments":[{"group":{"start":6,"value":"\"Sauce Labs Backpack\"","children":[{"start":7,"value":"Sauce Labs Backpack","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":9,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I click the cart icon","isBg":true,"stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":10,"keywordType":"Action","textWithKeyword":"When I click the checkout button","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":11,"keywordType":"Action","textWithKeyword":"And I enter checkout first name \"Abhishek\"","stepMatchArguments":[{"group":{"start":28,"value":"\"Abhishek\"","children":[{"start":29,"value":"Abhishek","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":44,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"And I enter checkout last name \"Gargya\"","stepMatchArguments":[{"group":{"start":27,"value":"\"Gargya\"","children":[{"start":28,"value":"Gargya","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":45,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"And I enter checkout zip code \"\"","stepMatchArguments":[{"group":{"start":26,"value":"\"\"","children":[{"start":27,"value":"","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":46,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"And I click the continue button","stepMatchArguments":[]},{"pwStepLine":47,"gherkinStepLine":15,"keywordType":"Outcome","textWithKeyword":"Then I should see \"Error: Postal Code is required\"","stepMatchArguments":[{"group":{"start":13,"value":"\"Error: Postal Code is required\"","children":[{"start":14,"value":"Error: Postal Code is required","children":[{"children":[]}]},{"children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end